### ISSUE TITLE
Reliance on libxmljs produces compilation error with node12

### ISSUE THREAD

**Issue by kaymccormick** [vberlier/docutils-parser#12]
See this issue: [libxmljs issue 546](https://github.com/libxmljs/libxmljs/issues/546)

**Comment by vberlier** [comment]
Hmm not sure what to do about this, besides waiting for a patch :/

**Comment by vberlier** [comment]
It seems like the issues with node 12 are finally resolved. I just published version 0.2.0 which now requires libxmljs version 0.19.7.
